[package]
name = "game"
version = "0.1.0"
edition = "2024"

[dependencies]
engine = { workspace = true }
anyhow = { workspace = true }
winit = { workspace = true }
glam = { workspace = true }
tokio = { version = "1.53.1", features = ["full"] }
tracing = { workspace = true }
itertools = { workspace = true }
tracing-subscriber = "0.3.23"
ordermap = "1.2.1"
