[package]
name = "game"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
engine = { workspace = true }
anyhow = { workspace = true }
glam = { workspace = true }
tokio = { version = "1.53.1", features = ["full"] }
tracing = { workspace = true }
itertools = { workspace = true }
tracing-subscriber = "0.3.23"
ordermap = "1.2.1"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
image = { version = "0.25.10", default-features = false, features = ["png"] }
static_assertions = "1.1.0"

[lints]
clippy.all = "allow"
