[package]
name = "render_graph_macros"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
convert_case = "0.12.0"
itertools = { workspace = true }
proc-macro-crate = "3.5.0"
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = { version = "3.0.4", features = ["full"] }

[lints]
workspace = true
