[profile.dev.package."*"]
opt-level = 3

[profile.release-lto]
inherits = "release"
codegen-units = 1
strip = "debuginfo"
lto = "fat"

[workspace]
resolver = "3"
members = ["harness", "game", "render_graph", "typemap", "engine", "genmap", "render_graph_macros"]

[workspace.dependencies]
typemap = { path = "./typemap" }
indexmap = { path = "./indexmap" }
genmap = { path = "./genmap" }
harness = { path = "./harness" }
engine = { path = "./engine" }
render_graph = { path = "./render_graph" }
anyhow = "1.0.104"
wgpu = "30.0.1"
tracing = "0.1.44"
winit = "0.30.13"
glam = { version = "0.33.6", features = ["bytemuck"] }
itertools = "0.15.0"
crevice = { version = "0.20.1", features = ["glam"] }

[workspace.package]
version = "0.1.0"
authors = ["Heavenstone <contact@heav.fr>"]
edition = "2024"

[workspace.lints.rust]
refining_impl_trait = "allow"

[workspace.lints.clippy]
# all = { level = "allow", priority = -2 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
iter_over_hash_type = "warn"
allow_attributes = "warn"
allow_attributes_without_reason = "warn"
clone_on_ref_ptr = "warn"
dbg_macro = "warn"
decimal_literal_representation = "warn"
default_numeric_fallback = "deny"
doc_paragraphs_missing_punctuation = "warn"
empty_enum_variants_with_brackets = "warn"
empty_structs_with_brackets = "warn"
error_impl_error = "forbid"
get_unwrap = "warn"
if_then_some_else_none = "warn"
infinite_loop = "warn"
let_underscore_must_use = "warn"
mod_module_files = "forbid"
module_name_repetitions = "warn"
renamed_function_params = "forbid"
same_name_method = "warn"
shadow_unrelated = "warn"
single_call_fn = "warn"
unnecessary_self_imports = "warn"
unused_trait_names = "warn"
wildcard_enum_match_arm = "warn"
map_err_ignore = "warn"
branches_sharing_code = "warn"
cast_lossless = "forbid"
cast_possible_truncation = "forbid"
cast_possible_wrap = "forbid"
cast_sign_loss = "forbid"
coerce_container_to_any = "deny"

implied_bounds_in_impls = "allow"
must_use_candidate = "allow"
missing_panics_doc = "allow" # I like this one but it has way-too annoying false-positives
too_many_lines = "allow"
items_after_statements = "allow"
missing_const_for_fn = "allow"
iter_on_empty_collections = "allow" # False positives
missing_errors_doc = "allow"
large_enum_variant = "allow" # If it is important this will be discovered anyway. Most times this does not matter.
significant_drop_tightening = "allow" # False positives on what consists of "usage"
