[workspace]
resolver = "3"
members = ["harness", "game", "render_graph", "typemap", "engine", "genmap"]

[workspace.dependencies]
typemap = { path = "./typemap" }
genmap = { path = "./genmap" }
harness = { path = "./harness" }
engine = { path = "./engine" }
render_graph = { path = "./render_graph" }
anyhow = "1.0.104"
wgpu = "30.0.1"
tracing = "0.1.44"
winit = "0.30.13"
glam = { version = "0.33.6", features = ["bytemuck"] }
itertools = "0.15.0"

[workspace.package]
version = "0.1.0"
authors = ["Heavenstone <contact@heav.fr>"]
edition = "2024"
