[package]
name = "engine"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
render_graph = { workspace = true }
harness = { workspace = true }
genmap = { workspace = true }

wgpu = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
winit = { workspace = true }
glam = { workspace = true, features = ["bytemuck"] }
pollster = "1.0.1"
itertools = { workspace = true }
bytemuck = { version = "1.25.2", features = ["derive"] }
parking_lot = { version = "0.12.5", features = ["arc_lock"] }
thiserror = "2.0.20"
crevice = { workspace = true }
static_assertions = "1.1.0"

[lints]
workspace = true
