[package]
name = "harness"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
render_graph = { workspace = true }
typemap = { workspace = true }

wgpu = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
winit = { workspace = true }
glam = { workspace = true, features = ["bytemuck"] }
pollster = "1.0.1"
itertools = { workspace = true }
bytemuck = "1.25.2"
parking_lot = "0.12.5"
thiserror = "2.0.20"

[lints]
workspace = true
